### ISSUE TITLE
Throwing error and catching it locally in JobsController

### ISSUE THREAD

**Issue by JeyM1** [AtlasRender/atlas-core#114]
**Describe the bug**
Throwing error and catching it locally in JobsController.

**Expected behavior**
Throwing valid error.

**Screenshots**
![image](https://user-images.githubusercontent.com/46285162/97606919-ff517d80-1a18-11eb-95ed-6b328fd66f2f.png)

**Comment by DanilAndreev** [comment]
Totally not a problem.
