### ISSUE TITLE
[Database] Saving plugin python file

### ISSUE THREAD

**Issue by JeyM1** [AtlasRender/atlas-core#13]
### Problem:
While saving python plugin file into DB, how we need to save it? Plain text | Binary | ...

**Comment by DanilAndreev** [comment]
I think nothing bat in saving script in plain text. We should choose encoding, such as utf-8 and save plugins. Or we can add field with encoding information.

**Comment by DanilAndreev** [comment]
In file it is metadata. We can figure out how to read this file using it. Also, script file can be stored as plain text.
