### ISSUE TITLE
Create AJW route params validator.

### ISSUE THREAD

**Issue by DanilAndreev** [AtlasRender/atlas-core#136]
# Feature request
## Is your feature request related to a problem? Please describe.

Create AJW based route params validator.  
For example, I need mechanism for validating route:
___/jobs/:jobId___  
I want to check is __-jobId___ integer.

## Describe the solution you'd like 🌟

AJW middleware.

## Describe alternatives you've considered 🐾

None

**Comment by JeyM1** [comment]
You can use [paramsValidator](https://github.com/AtlasRender/atlas-core/blob/6451a244b0fbb702b9df9cfd457fa5c27c1228d6/src/utils/ajv-middleware/ajv-validation-middleware.ts#L85).
Usage is the same as with bodyValidator:
- provide validation schema
- provide AJV instance.

**Comment by JeyM1** [comment]
And also it's AJV (Another Json Validator), not AJW xD
