### ISSUE TITLE
Please create frame range object

### ISSUE THREAD

**Issue by Who1sthatdude** [AtlasRender/atlas-core#144]
# Feature request
## Is your feature request related to a problem? Please describe.
Frame range should take an object instead of string in controller route __[POST]__ ___/jobs___

## Describe the solution you'd like 🌟
Object has fields:
```
{
    frameStart: number,
    frameEnd: number,
    step: number,
    startFrom: number,
    renumStep: number
}
```

## Describe alternatives you've considered 🐾
none

## Additional context 👍:
none

**Comment by DanilAndreev** [comment]
# Added new frame range system. 
### Frame range item looks like:
```javascript
{
  start: number;
  end: number;
  step: number;
  renumberrStart: number;
  renumberStep: number;
}
```

You should send to __Core__ an array of frame range items.
