### ISSUE TITLE
[Database] Global plugins updating

### ISSUE THREAD

**Issue by JeyM1** [AtlasRender/atlas-core#15]
### Problem:
While adding global plugin to organisation plugins at start, we need some way to keep copied plugin updated (i.e. while global plugin is updated, update the same plugin in organisation).
### Ideas:
- Plugin versioning

**Comment by DanilAndreev** [comment]
Plugin swill have __semantic versioning__. So, updated plugin will be a new record and user should update plugin version by himself.
