### ISSUE TITLE
Can`t get tasks

### ISSUE THREAD

**Issue by ZaykaNya** [AtlasRender/atlas-core#181]
# Describe the bug 👀

Can`t get tasks of job from database with route: __[GET]__ ___/:jobs___.
Do not have organization with jobs.

## Expected behavior 🙌
Send organization with job and task. Fix bug with permissions.

## Screenshots ✨

![image](https://user-images.githubusercontent.com/48089558/100554294-6f635580-329c-11eb-97d2-71230f87c3c0.png)

**Comment by DanilAndreev** [comment]
You should get this information using route:  
__[GET]__ ___/jobs/:jobId/tasks___  
If you want to get details about one task:  
__[GET]__ ___/jobs/:jobId/tasks/:taskId___
